# Generated by Django 4.2.2 on 2023-06-14 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("send", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="file", name="file", field=models.FileField(upload_to="file"),
        ),
    ]
